{% set name = "lua-compat-5.3-c" %}
{% set version = "0.10" %}

package:
  name: {{ name }} 
  version: {{ version }}

source:
  url: https://github.com/lunarmodules/lua-compat-5.3/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d1ed32f091856f6fffab06232da79c48b437afd4cd89e5c1fc85d7905b011430

build:
  number: 0
  skip: true  # [win]

test:
  commands:
    - test -f ${PREFIX}/include/lua-compat-5.3/c-api/compat-5.3.h
    - test -f ${PREFIX}/include/lua-compat-5.3/c-api/compat-5.3.c

about:
  home: https://github.com/lunarmodules/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Compatibility module providing Lua-5.3-style APIs for Lua 5.2 and 5.1 (C API only)

extra:
  recipe-maintainers:
    - danielnachun
